<?php

use Illuminate\Database\Seeder;

class topicTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $content = "
    	</h3>Nội dung tin tức: Demo Project Laravel 5.3</h3>
    	<p>
    	<b>Địa chỉ </b>: TPHCM<br>
    	<b>Website</b>: http://codeguideline.nv<br>
    	</p>
    	";
    	DB::table('topic')->insert([
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 1, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 1, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 1, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 1, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 1, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 2, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 2, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 2, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 2, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 2, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 3, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 3, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 3, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 3, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 3, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 4, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 4, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 4, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 4, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 4, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 5, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 5, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 5, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 5, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 5, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 6, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 6, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 6, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 6, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 6, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 7, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 7, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 7, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 7, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 7, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 8, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 8, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 8, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 8, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 8, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 9, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 9, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 9, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 9, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()],
        	['tittle' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','shortdescription' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','content' => $content,'image' => 'FPT-2.jpg','status' => 1,'viewed' => 20, 'idCatagory' => 9, 'idTag' => '1,2,3', 'approvestatus' => 1, 'approvedby' => 'Admin_1', 'idUser'=> 21,'created_at' => new DateTime()]
        	]);
    }
}
